//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlogicContabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class plancuentas
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<decimal> debeini { get; set; }
        public Nullable<decimal> haberini { get; set; }
        public Nullable<decimal> saldoini { get; set; }
        public Nullable<decimal> acumini { get; set; }
        public Nullable<decimal> acumhaber { get; set; }
        public Nullable<decimal> acumsaldo { get; set; }
        public Nullable<decimal> acumdebe { get; set; }
    }
}
